metallica="dad",'asdasdas',19243
art,dan,yr=metallica
print(art)
print(dan)
print(yr)
metallica2=['dasda','saiukj',1922]
print(metallica2)
metallica2.append("rock")
print(metallica2)
title,artist,year,banda=metallica2
print(artist,title,year,banda)